spring:
  datasource:
    url: jdbc:postgresql://psinder-db-kominikdowalczyk-2e25.k.aivencloud.com:10368/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_P5FYt-yr0reofuxhpnp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.dkowalczyk.psinder_app: DEBUG
    org.springframework.security: DEBUG